### ISSUE TITLE
Can't revision precached assets in imported script

### ISSUE THREAD

**Issue by jschumme** [ragingwind/next-workbox#1]
First of all, great plugin!

I'd like to import my own workbox-script by using

```
 workbox: {
   registerSW: true,
   importScripts: [
      '../custom-sw.js'
    ]
 }
```

unfortunately that yields the following import order in sw.js

```
importScripts(
  "/static/workbox/workbox-v3.0.1/workbox-sw.js",
  "../custom-sw.js",
  "/static/workbox/next-precache-manifest-ea5e234c445a03e56ecb68a34810ce23.js"
);
```

In custom-sw.js I have no access to the revision number and can't do something like:

```
const rev = self.__precacheManifest[0].revision
workbox.precaching.precacheAndRoute([
  {
    url: '/test',
    revision: rev
  },
```

Any ideas?
Thanks!

**Comment by ragingwind** [comment]
Not like workbox-webpack-plugin, this plugin uses revision in file postfix name instead of revision filed in config of workbox. Because, next.js chunk and pages are generated already with [rev postfix filename](https://next-hnpwa.now.sh/static/workbox/next-precache-manifest-3ca95f5a1d71a0880d470827d3ff877f.js). 

So, I recommend that

- generating own hash value for revision field
- using workobox with [glob options](https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin#configuration)
